apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-site-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-site
  template:
    metadata:
      labels:
        app: internal-site
    spec:
      containers:
        - name: internal-site
          image: pripan317/internalsite:latest
